# Generated by Django 4.1.5 on 2023-07-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="myuser",
            old_name="id_delete",
            new_name="is_delete",
        ),
    ]
