# Generated by Django 4.1.5 on 2023-07-25 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=20, verbose_name="作者名字")),
                ("plays", models.IntegerField(default=0, verbose_name="作品总数")),
                ("fans", models.IntegerField(default=0, verbose_name="粉丝总数")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "作者信息",
                "verbose_name_plural": "作者信息",
                "db_table": "author_info_table",
            },
        ),
        migrations.CreateModel(
            name="NovelsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=20, verbose_name="类型名")),
            ],
            options={
                "verbose_name": "小说类型",
                "verbose_name_plural": "小说类型",
                "db_table": "novels_type_table",
            },
        ),
        migrations.CreateModel(
            name="NovelsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("title", models.CharField(max_length=30, verbose_name="小说标题")),
                ("description", models.TextField(verbose_name="小说简介")),
                ("watcher", models.IntegerField(default=0, verbose_name="总观看数")),
                ("words", models.IntegerField(default=0, verbose_name="总字数")),
                ("collections", models.IntegerField(default=0, verbose_name="总收藏数")),
                ("comments", models.IntegerField(default=0, verbose_name="总评论数")),
                ("chapters", models.IntegerField(default=0, verbose_name="总章节")),
                ("is_end", models.BooleanField(default=False, verbose_name="是否完结")),
                (
                    "image",
                    models.ImageField(upload_to="novels_image/", verbose_name="小说封面"),
                ),
                (
                    "author_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novel.authorinfo",
                        verbose_name="作者",
                    ),
                ),
                (
                    "novels_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novel.novelstype",
                        verbose_name="类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "小说信息",
                "verbose_name_plural": "小说信息",
                "db_table": "novels_info_table",
            },
        ),
        migrations.CreateModel(
            name="NovelChapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("title", models.CharField(max_length=20, verbose_name="章节名")),
                ("content", models.FileField(upload_to="novels/", verbose_name="章节内容")),
                (
                    "novels_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="novel.novelsinfo",
                        verbose_name="关联的小说",
                    ),
                ),
            ],
            options={
                "verbose_name": "小说章节",
                "verbose_name_plural": "小说章节",
                "db_table": "novel_chapters_table",
            },
        ),
    ]
