# Generated by Django 4.1.5 on 2023-07-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NovelsRotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("name", models.CharField(max_length=10, verbose_name="名称")),
                ("image", models.ImageField(upload_to="rotations/", verbose_name="图片")),
            ],
            options={
                "verbose_name": "首页小说轮播图",
                "verbose_name_plural": "首页小说轮播图",
                "db_table": "novels_rotation_table",
            },
        ),
    ]
