# Generated by Django 4.1.5 on 2023-07-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0002_novelsrotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novelchapters",
            name="title",
            field=models.CharField(max_length=50, verbose_name="章节名"),
        ),
    ]
