# Generated by Django 4.1.5 on 2023-07-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0003_alter_novelchapters_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="novelsinfo",
            name="sales",
            field=models.IntegerField(default=0, verbose_name="总销量"),
        ),
    ]
