# Generated by Django 4.1.5 on 2023-07-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0005_novelstype_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novelstype",
            name="logo",
            field=models.CharField(default="", max_length=20, verbose_name="类型标记"),
        ),
    ]
